##############################
# Please edit this line to "not_sample_anymore" to make the bot run
is_example_config_or_not: "not_sample_anymore"
##############################
bot_token: "1494873130:AAHhhCmVIYV2Z9pyjf-gWYkC9zulqtoleFA"
api_key: '1233635'
api_hash: '7bcc363ceb406bf64deb476685a79ab5'
owner_id: 1156110551
owner_username: "rian1337"
message_dump: "-1007777777777"
gban_dump: "CHAT ID"
load: []
no_load: []
strict_antispam: False
workers: 4
deepfry_token: None
del_cmds: False
sw_api: ''
port: '8483'

# Database
database_url: "postgres://dvhbrdgztsdelm:7b753bdc85145fdfac6200c6f5a561b7dbcb6e2f67f4f88b7bbb055fc2f1bc96@ec2-54-158-190-214.compute-1.amazonaws.com:5432/d403bqu7rfkke0"

# Permission
sudo_users: []
support_users: []
whitelist_users: []
